title: Tingting Dan
title_cn: 但婷婷
logo: /assets/img/wei.jpg
description: Ph.D student @SCUT.
show_buttons: true
index_url: https://dandy5721.github.io/dandy.github.io
project_url: https://dandy5721.github.io/dandy.github.io/projects
publication_url: https://dandy5721.github.io/dandy.github.io/publications
research_statement_url: https://drive.google.com/file/d/1SJgMNn493hlpMTHLE5goz4pCxzj5oLuJ/view?usp=sharing
twitter_url: https://twitter.com/DanTingting
linkedin_url: https://scholar.google.com/citations?user=FMcmg0gAAAAJ&hl=en&oi=ao
rg_url: https://www.researchgate.net/profile/Tingting_Dan
google_analytics:
theme: jekyll-theme-minimal
