title: Tingting Dan
title_cn: 但婷婷
logo: /assets/img/wei.jpg
description: Ph.D student @SCUT.
show_buttons: true
index_url: https://dandy5721.github.io
project_url: https://dandy5721.github.io/dandy.github.io/blob/main/projects
publication_url: https://github.com/Dandy5721/dandy.github.io/blob/main/publications
research_statement_url: https://drive.google.com/file/d/1SJgMNn493hlpMTHLE5goz4pCxzj5oLuJ/view?usp=sharing
twitter_url: https://twitter.com/DanTingting
linkedin_url: https://www.linkedin.com/in/%E6%A2%93%E6%B3%89-%E9%AD%8F-275800215/
rg_url: https://www.researchgate.net/profile/Tingting_Dan
google_analytics:
theme: jekyll-theme-minimal
